### ISSUE TITLE
Error when running Chocolatey

### ISSUE THREAD

**Issue by borkin8r** [telyn/docker-chocolatey#1]
When attempting to run `choco.exe pack <path to nuspec>` in the container, via drone, I get the following errors:
`/usr/bin/choco.exe: MZ????@???: not found`
`/usr/bin/choco.exe: Syntax error: word unexpected (expecting ")")`

Do you know what may be causing these errors?

**Comment by telyn** [comment]
I think you need to run `mono /usr/bin/choco.exe pack <path to nuspec>`.

I recently discovered that choco has its own Dockerfile over at https://github.com/chocolatey/choco/blob/master/docker/Dockerfile.linux - might be a better shout than continuing to use mine. Even comes with a wrapper 😁

**Comment by borkin8r** [comment]
Thanks, I'll give both of them a try! 😁
